server:
  port: 2021

spring:
  application:
    name: servicio-items

#servicio-productos:
#  ribbon:
#    listOfServers: localhost:2020, localhost:2022

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    preferIpAddress: true
#
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 13000

ribbon:
  ConnectTimeout: 3000
  ReadTimeout: 10000
