spring:
  application:
    name: servicio-apigateway-server
  cloud:
    gateway:
      routes:
        - id: servicio-productos
          uri: lb://servicio-productos
          predicates:
            - Path=/api/productos/**
          filters:
              - StripPrefix=2
              - name: Ejemplo
                args:
                  mensaje: Hola, este es mi mensaje personalizado
                  cookieNombre: Usuario
                  cookieValor: MateoSilva
        - id: servicio-items
          uri: lb://servicio-items
          predicates:
              - Path=/api/items/**
              - Header= token
              - Header= Content-Type, application/json
              - Method= POST, GET
              - Query= color
              - Cookie= color, azul
          filters:
            - StripPrefix=2
            - AddRequestHeader= token-request, 123456
            - AddResponseHeader= token-response, 12345678
            - AddRequestParameter= nombre, Mateo
#            - name: Ejemplo
#              args:
#                mensaje: Hola, este es mi mensaje personalizado
#                cookieNombre: Usuario
#                cookieValor: MateoSilva
server:
  port: 8090

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
